### ISSUE TITLE
More explanation on API docs

### ISSUE THREAD

**Issue by stezarpriansya** [carloabimanyu/fastapi#1]
Hi Carlo, this is a good example of repository. Good job!

I have a feedback for you, maybe you must try to explain all of your endpoints on API documentation and add more calculation on one of your endpoints.

Thanks.

**Comment by carloabimanyu** [comment]
Thank you so much for the knowledge and sharing, Mas Stezar. It means lot to me.

**Comment by stezarpriansya** [comment]
> > Hi Carlo, this is a good example of repository. Good job!
> > I have a feedback for you, maybe you must try to explain all of your endpoints on API documentation and add more calculation on one of your endpoints.
> > Thanks.
> 
> Thank you so much for the knowledge and sharing, Mas Stezar. It means lot to me.

Keep learn, practice, and always do the best ya!
